### PR TITLE
Lineage pull request for: skeleton

### LINKED ISSUE #16: Fix failing tests
# 💥 Regression Report

Our APB runs on this repository keep erroring out because of some failed tests.  See [this APB run](https://github.com/cisagov/ioc-scanner/runs/1054706095?check_suite_focus=true), for example.

## Last working version

Looks like [this](https://github.com/cisagov/ioc-scanner/actions/runs/181727101) was the last build that succeeded.

## To Reproduce

- Check out the repo from scratch
- Install Python dependencies
- Run tests

## Expected behavior

All tests should pass.

### PR DESCRIPTION
**Pull request by cisagovbot**
# Lineage Pull Request #

[Lineage] has created this pull request to incorporate new changes found in an
upstream repository:

Upstream repository: [`https://github.com/cisagov/skeleton-python-library.git`](https://github.com/cisagov/skeleton-python-library.git)
Remote branch: `HEAD`

Check the changes in this pull request to ensure they won't cause issues with
your project.

------------

**Note:** *You are seeing this because one of this repository's maintainers has
configured [Lineage] to open pull requests.*

For more information:

🛠 [Lineage] configurations for this project are stored in `.github/lineage.yml`

📚 [Read more about Lineage][Lineage]

[//]: # (lineage:metadata:{&quot;slayed&quot;:true})
[Lineage]: https://github.com/cisagov/action-lineage/ "Lineage GitHub Action"

### CODE REVIEW

**Review by felddy — APPROVED** [review]

**Comment by felddy** [comment]
@mcdonnnj  please take a look at the failing tests.  Looks like the fake filesystem needs some `/dev` love.

**Comment by mcdonnnj** [comment]
> 
> 
> @mcdonnnj please take a look at the failing tests. Looks like the fake filesystem needs some `/dev` love.

@felddy This appears to be an issue with the new `pytest` 6 release. As you can see [here](https://github.com/cisagov/ioc-scanner/runs/943348889), if I pin `pytest < 6` in `setup.py`, tests pass with no issue. I'll have to see what changed in v6 that caused a failure in `pyfakefs`.

**Review by jsf9k — APPROVED** [review]
:eye: :heavy_check_mark:

**Review by dav3r — APPROVED** [review]
Strong work and nice sleuthing with that pytest-/dev/null thang!  🚀

**Pull request merged**
